import pandas as pd
from pymongo.errors import PyMongoError
from src.database.database_mongo import get_mongo_db

# Caminho do arquivo CSV processado
file_path = "../../data/cleaned_data/Arquivo_CSV_de_Vendas_cleaned.csv"

try:
    # Carregar o dataset modificado
    df = pd.read_csv(file_path)
    print("üìÇ Dataset carregado com sucesso!")

    # Conectar ao MongoDB
    db = get_mongo_db()
    collection_name = "vendas"
    collection = db[collection_name]

    # Converter DataFrame para dicion√°rios e inserir no MongoDB
    data = df.to_dict(orient="records")
    collection.insert_many(data)

    print(f"‚úÖ Dados inseridos com sucesso na cole√ß√£o '{collection_name}' do MongoDB!")

except FileNotFoundError:
    print(f"‚ùå Erro: O arquivo '{file_path}' n√£o foi encontrado. Verifique o caminho.")
except pd.errors.EmptyDataError:
    print("‚ùå Erro: O arquivo CSV est√° vazio.")
except pd.errors.ParserError:
    print("‚ùå Erro: Falha ao processar o arquivo CSV. Verifique o formato.")
except PyMongoError as e:
    print(f"‚ùå Erro ao inserir dados no MongoDB: {e}")
except Exception as e:
    print(f"‚ùå Erro inesperado: {e}")
